### ISSUE TITLE
Demo world mining drone derps out & LoadARMS bug

### ISSUE THREAD

**Issue by jjtParadox** [Rynchodon/ARMS#122]
Now that the ore scanner's fixed, I've noticed the mining bot is failing to dock with the mining station after it goes on a mining run. It docks correctly before it goes on any runs, but after it goes to the asteroid it approaches the docking port at the wrong angle, gets within 50 meters, turns around, boosts away from the station for a good 100 meters or so at a different angle, approaches the port at another wrong angle, and repeats ad infinitum.

This seems specific to only the mining drone, as the other two docking drones (retriever and ingot transport) seem to dock just fine.

[log-0.txt](https://github.com/Rynchodon/ARMS/files/568148/log-0.txt)

There's also a bug with LoadARMS that's preventing the use of a locally compiled version of ARMS, so the above log is lacking debug info because I can't figure out how to enable debug logging without a locally compiled version, sorry 😢 

LoadARMS log:
```
11/2/2016 9:56:50 PM: Game launched
11/2/2016 9:56:50 PM: Downloading update: v1.76.2.0-stable-unstable
System.AggregateException: One or more errors occurred. ---> System.IO.IOException: The file 'C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Bin64\ARMS.dll' already exists.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   at System.IO.Compression.ZipFileExtensions.ExtractToDirectory(ZipArchive source, String destinationDirectoryName)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding)
   at Rynchodon.ArmsUpdater.DownloadAsset(Release bestRelease, Asset asset)
   at Rynchodon.ArmsUpdater.UpdateArms()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Rynchodon.Injector.DllInjector.Run()
   at Rynchodon.Injector.DllInjector.Main(String[] args)
---> (Inner Exception #0) System.IO.IOException: The file 'C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Bin64\ARMS.dll' already exists.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   at System.IO.Compression.ZipFileExtensions.ExtractToDirectory(ZipArchive source, String destinationDirectoryName)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding)
   at Rynchodon.ArmsUpdater.DownloadAsset(Release bestRelease, Asset asset)
   at Rynchodon.ArmsUpdater.UpdateArms()
   at System.Threading.Tasks.Task.Execute()<---
```

**Comment by Rynchodon** [comment]
Sorry, I missed the notification. Are you able to build ARMS now?

FYI the compiler removes debug info from the release version so it is only possible to debug with the appropriate build.

**Comment by jjtParadox** [comment]
I was able to compile ARMS in debug mode, but LoadARMS wasn't allowing me to use the local version of the .dll produced. I'll check if the issue persists when I get back to my main machine. Thanks!

**Comment by jjtParadox** [comment]
Alright the drone docks just fine now. It mines a little strange, but doesn't seem to completely fail, so that'll be good enough for me. Thanks for the help.
